Thanhnb/k8s springboot pod manage
vntechies/blog pull request #20
Opened 2023-01-29 16:32 UTC by nbthanh98

- Add content ReplicationController, Deployment

2023-02-09 11:32 UTC, qmau94 requested changes
@nbthanh98 nice posts, cảm ơn em.

check lại comment giúp anh nhé.

2023-02-09 11:32 UTC, qmauvnt commented on data/courses/k8s-spring-boot/quan-ly-pod-voi-replicationController-deployment.mdx
> +Ở bài [trước](https://vntechies.dev/courses/k8s-spring-boot/trien-khai-springboot-container-tren-kubernetes-voi-pods) thì chúng ta đã đóng gói container ứng dụng với pod và triển khai pod trực tiếp t
```suggestion
Ở bài [trước](/courses/k8s-spring-boot/trien-khai-springboot-container-tren-kubernetes-voi-pods), chúng ta đã đóng gói container ứng dụng với pod và triển khai pod trên Kubernetes. Tuy nhiên, cách khai trực tiếp này có một số vấn đề. Giả sử vì một lý do nào đó mà pod chạy ứng dụng bị crash hoặc bị xóa mất, lúc này các request gọi vào ứng dụng sẽ bị lỗi. Để giải quyết vấn đề trên, chúng ta có thể tăng số lượng pod chạy ứng dụng và phải đảm bảo một số lượng pod nhất định cùng chạy trên một thời điểm để khi một pod bị lỗi thì các request gọi vào ứng dụng vẫn được xử lý bởi các pod còn lại.
```

2023-02-09 11:32 UTC, qmauvnt commented on data/courses/k8s-spring-boot/quan-ly-pod-voi-replicationController-deployment.mdx
> +Ở phần này thì chúng ta sẽ tìm hiểu cách tạo và quản lý Pod với ReplicationController thông qua việc triển khai ứng dụng spring boot.
```suggestion
Ở phần này, chúng ta sẽ tìm hiểu cách tạo và quản lý Pod với ReplicationController thông qua việc triển khai một ứng dụng spring boot.
```

2023-02-09 11:32 UTC, qmauvnt commented on data/courses/k8s-spring-boot/quan-ly-pod-voi-replicationController-deployment.mdx
> +ReplicationController object trong Kubernetes, object này được sử dụng khi chúng ta muốn đảm bảo số lượng pod nhất định chạy trên cùng một thời điểm. Khi có một pod nào đó bị lỗi hoặc bị xóa thì sẽ c
```suggestion
ReplicationController là một object của Kubernetes được sử dụng để đảm bảo số lượng pod nhất định chạy trên cùng một thời điểm. Khi có một pod nào đó bị lỗi hoặc bị xóa, một pod mới sẽ được tạo để đảm bảo số lượng pod chạy trên cùng một thời điểm. Bạn có thể tham khảo thêm về ReplicationController ở [docs chính thức của Kubernetes](https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/).
```

2023-02-09 11:32 UTC, qmauvnt commented on data/courses/k8s-spring-boot/quan-ly-pod-voi-replicationController-deployment.mdx
> +Thay vì định nghĩa và triển khai pod một cách trực tiếp thì sẽ dùng ReplicationController để tạo và quản lý pod nhằm đảm bảo số lượng pod chạy trên cùng một thời điểm. Chúng ta mong muốn có thể chạy
@nbthanh98 có bị lặp ý với phần trên không?

2023-02-09 11:32 UTC, qmauvnt commented on data/courses/k8s-spring-boot/quan-ly-pod-voi-replicationController-deployment.mdx
> +  replicas: 3 # Số lượng Pod muốn chạy trên một thời điểm.
```suggestion
  replicas: 3 # Số lượng Pod muốn chạy tại một thời điểm.
```

2023-02-09 11:32 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-pod-voi-replicationController-deployment.mdx
> +  # Kiểm tra image tag của po `k8s-springboot-series-wlbps` mới được tạo bởi ReplicationController.
```suggestion
  # Kiểm tra image tag của pod `k8s-springboot-series-wlbps` mới được tạo bởi ReplicationController.
```

2023-02-09 11:32 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-pod-voi-replicationController-deployment.mdx
> +  `ReplicationController` sẽ đảm bảo số lượng pod chạy trên Kubernetes cluster trong cùng một thời điểm. Để định nghĩa số lượng pod mong muốn thì sử dụng `replicas`, ví dụ trên thì đang định nghĩa `r
```suggestion
  `ReplicationController` sẽ đảm bảo số lượng pod chạy trên Kubernetes cluster trong cùng một thời điểm. Để định nghĩa số lượng pod mong muốn ta sử dụng `replicas`. Trong ví dụ trên, chúng ta đang định nghĩa `replicas: 3`. Để tăng/giảm số lượng pod, chúng ta có thể sửa trong `ReplicationController` YAML file tại trường `replicas`, hoặc sử dụng lệnh `kubectl scale rc <replicationController-name> --replicas=<pod-number>`.
```

2023-02-09 11:32 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-pod-voi-replicationController-deployment.mdx
> +Ở bài viết sau chúng ta sẽ tìm hiểu về cách truy cập ứng dụng từ bên ngoài cụm Kubernetes và cách các ứng dụng gọi nhau trong cụm Kubernetes.
```suggestion
Ở bài viết sau chúng ta sẽ tìm hiểu về cách truy cập ứng dụng từ bên ngoài cụm Kubernetes và cách các ứng dụng kết nối, liên lạc với nhau bên trong cụm Kubernetes.
```

2023-02-11 11:53 UTC, nbthanh98 commented
Cảm ơn anh @qmau94 đã review 
- Đã applied suggestions.
- Thêm một số thay đổi ở commit [này](https://github.com/vntechies/blog/pull/20/commits/6dba40a16797502f000a086736224cd165c6e8c8). Anh @qmau94 review thêm giúp em nhé.

2023-02-11 15:56 UTC, qmau94 approved these changes
[![LGTM](https://www.lgtm.app/p/u54UH64UX)](https://www.lgtm.app/i/u54UH64UX)

2023-02-11 15:57 UTC, merged