Update content spring boot k8s series
vntechies/blog pull request #27
Opened 2023-04-08 17:16 UTC by nbthanh98

Add contents:
  - Service in Kubernetes.
  - ConfigMap and Secret in Kubernetes.
 
Update contents:
  - Container and Pod Kubernetes.
  - Pod manage with ReplicationController and Deployment.
  
Anh @qmau94 review giúp em PR này với ạ.

2023-04-08 18:18 UTC, qmau94 requested changes
@nbthanh98 nice updates em ơi, cảm ơn vì đã contribute

anh có add một số comments, em check lại nhé!

2023-04-08 18:18 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +Trong bài viết này chúng ta cùng nhau tìm hiểu hai đối tượng giúp lưu trữ những cấu hình đó là ConfigMap và Secret trong Kubernetes. Để tránh cho bài viết này bị trùng lặp thì mình sẽ chỉ cấu hình St
```suggestion
Trong bài viết này chúng ta cùng nhau tìm hiểu hai đối tượng giúp lưu trữ những cấu hình, đó là ConfigMap và Secret trong Kubernetes. Để tránh bị trùng lặp, mình sẽ chỉ cấu hình Students-service, còn Courses-service cũng sẽ có cấu hình tương tự.
```

2023-04-08 18:18 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +Bạn có thể tìm hiểu thêm Secret tại [trang web chính thức của Kubernetes](https://kubernetes.io/docs/concepts/configuration/secret/).
```suggestion
Bạn có thể tìm hiểu thêm về Secret tại [trang web chính thức của Kubernetes](https://kubernetes.io/docs/concepts/configuration/secret/).
```

2023-04-08 18:18 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +Bạn có thể tìm hiểu thêm ConfigMap tại [trang web chính thức của Kubernetes](https://kubernetes.io/docs/concepts/configuration/configmap/).
```suggestion
Bạn có thể tìm hiểu thêm về ConfigMap tại [trang web chính thức của Kubernetes](https://kubernetes.io/docs/concepts/configuration/configmap/).
```

2023-04-08 18:18 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +ConfigMap là đối tượng khá đơn giản để định nghĩa trong Kubernetes, các thông tin cấu hình thì định nghĩa dưới trường `data` theo format key=value và tên của ConfigMap thì định nghĩa ở trường `metada
```suggestion
ConfigMap là đối tượng khá đơn giản để định nghĩa trong Kubernetes, các thông tin cấu hình thì định nghĩa dưới trường `data` theo format key=value, tên của ConfigMap được định nghĩa tại trường `metadata.name`.
```

2023-04-08 18:18 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +- **Sử dụng biến môi trường**: Thường sử dụng cho các thông tin cấu hình không quá lớn (< 1MB). Khi thay đổi thông tin cấu hình ở ConfigMap thì các Pod **CẦN** restart lại để cập nhật thông tin cấu h
có thể lý giải sự khác biệt giữa 2 cách sử dụng configmap theo link này để tránh nhầm lẫn https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically

2023-04-08 18:18 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +Khi thực hiện cập nhật ConfigMap thì file config "application.yaml" được mouted vào container trước đó cũng sẽ thay đổi theo mà Pod không cần restart. Nhưng vì Spring Boot thường để cấu hình thành be
tránh dùng cách diễn đạt gì đó, có thể cho phần trong ngoặc đơn thay từ gì đó

2023-04-08 18:18 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +- **Sử dụng biến môi trường**: Giống với ConfigMap các thông tin trong Secret sẽ được inject vào trong container và khi thay đổi thông tin cấu hình ở Secret thì các cũng Pod **CẦN** restart lại để cậ
tương tự như comment trên với configmap

2023-04-08 18:18 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +Trong bài này chúng ta đã tìm hiểu hai đổi tượng ConfigMap và Secret trong Kubernetes để lưu trữ các thông tin cấu hình của ứng dụng. Cũng đã tìm hiểu cấu hình ứng dụng cũng có thể lấy dữ liệu ở Conf
thông qua 2 cách

2023-04-08 18:18 UTC, qmau94 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +Trong bài này chúng ta đã tìm hiểu hai đổi tượng ConfigMap và Secret trong Kubernetes để lưu trữ các thông tin cấu hình của ứng dụng. Cũng đã tìm hiểu cấu hình ứng dụng cũng có thể lấy dữ liệu ở Conf
hãy xem xét yêu cầu của ứng dụng để lựa chọn cách sử dụng configmap và secret phù hợp

2023-04-11 16:48 UTC, nbthanh98 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +Khi thực hiện cập nhật ConfigMap thì file config "application.yaml" được mouted vào container trước đó cũng sẽ thay đổi theo mà Pod không cần restart. Nhưng vì Spring Boot thường để cấu hình thành be
Em đã update ở commit [này](https://github.com/vntechies/blog/commit/fbc39ba43dacba81a6ee97bcd55e1753f5397654).

2023-04-11 16:49 UTC, nbthanh98 commented on data/courses/k8s-spring-boot/quan-ly-cau-hinh-ung-dung-voi-configmap-va-secret.mdx
> +Trong bài này chúng ta đã tìm hiểu hai đổi tượng ConfigMap và Secret trong Kubernetes để lưu trữ các thông tin cấu hình của ứng dụng. Cũng đã tìm hiểu cấu hình ứng dụng cũng có thể lấy dữ liệu ở Conf
Em đã update ở commit [này](https://github.com/vntechies/blog/commit/4f103daa30e2844e17297df57f108921efd2ca97).

2023-04-17 02:20 UTC, qmau94 commented
LGTM, cảm ơn người em @nbthanh98 <3

2023-04-24 11:14 UTC, qmauvnt approved these changes

2023-04-24 11:14 UTC, merged

2023-04-24 11:15 UTC, qmau94 commented
@nbthanh98 cảm ơn người em vì PR này! keep up the good work nhé ❤️